/*
 * common_def.h
 *
 *  Created on: Dec 2, 2025
 *      Author: erenegdemir
 */

#ifndef INC_USERLIBRARIES_COMMON_DEF_H_
#define INC_USERLIBRARIES_COMMON_DEF_H_

#define TRUE		1
#define FALSE		0

typedef enum {
	HOME = 0,
	PROGRAMS,
	SETTINGS,
	COOKING,
	COOKING_TEMPCHANGE,
	COOKING_PWRCHANGE,
	COOKING_DURATION,
	SETTINGS_PI,
	SETTINGS_PI_KP,
	SETTINGS_PI_KI,
	SETTINGS_PI_SLEW,
	SETTINGS_PI_MAXPOWER,
	SETTINGS_TEMPOFFSET,
	SETTINGS_TEMPOFFSET_S1,
	SETTINGS_TEMPOFFSET_S2,
	SETTINGS_TEMPOFFSET_S3,
	SETTINGS_TEMPOFFSET_S4,
	SETTINGS_TEMPOFFSET_S5,
	SETTINGS_TIMEDATE,
	SETTINGS_TIMEDATE_HOUR,
	SETTINGS_TIMEDATE_MINUTE,
	SETTINGS_TIMEDATE_DAY,
	SETTINGS_TIMEDATE_MONTH,
	SETTINGS_TIMEDATE_YEAR,
	PROGRAMS_FASTSTART,
	PROGRAMS_FASTSTART_TEMP,
	PROGRAMS_FASTSTART_RISETIME,
	PROGRAMS_FASTSTART_FALLTIME,
	PROGRAMS_FASTSTART_DURATION,
	PROGRAMS_ADVTEMPCTRL,
	PROGRAMS_ADVTEMPCTRL_RISINGTIME,
	PROGRAMS_ADVTEMPCTRL_RISINGTIME_S1,
	PROGRAMS_ADVTEMPCTRL_RISINGTIME_S2,
	PROGRAMS_ADVTEMPCTRL_RISINGTIME_S3,
	PROGRAMS_ADVTEMPCTRL_RISINGTIME_S4,
	PROGRAMS_ADVTEMPCTRL_RISINGTIME_S5,
	PROGRAMS_ADVTEMPCTRL_RISINGTIME_S6,
	PROGRAMS_ADVTEMPCTRL_GENERATE,
	PROGRAMS_ADVTEMPCTRL_T1,
	PROGRAMS_ADVTEMPCTRL_T1_TEMP,
	PROGRAMS_ADVTEMPCTRL_T1_DUR,
	PROGRAMS_ADVTEMPCTRL_T1_SETRESET,
	PROGRAMS_ADVTEMPCTRL_T2,
	PROGRAMS_ADVTEMPCTRL_T2_TEMP,
	PROGRAMS_ADVTEMPCTRL_T2_DUR,
	PROGRAMS_ADVTEMPCTRL_T2_SETRESET,
	PROGRAMS_ADVTEMPCTRL_T3,
	PROGRAMS_ADVTEMPCTRL_T3_TEMP,
	PROGRAMS_ADVTEMPCTRL_T3_DUR,
	PROGRAMS_ADVTEMPCTRL_T3_SETRESET,
	PROGRAMS_ADVTEMPCTRL_T4,
	PROGRAMS_ADVTEMPCTRL_T4_TEMP,
	PROGRAMS_ADVTEMPCTRL_T4_DUR,
	PROGRAMS_ADVTEMPCTRL_T4_SETRESET,
	PROGRAMS_ADVTEMPCTRL_T5,
	PROGRAMS_ADVTEMPCTRL_T5_TEMP,
	PROGRAMS_ADVTEMPCTRL_T5_DUR,
	PROGRAMS_ADVTEMPCTRL_T5_SETRESET,
	PROGRAMS_ADVTEMPCTRL_T6,
	PROGRAMS_ADVTEMPCTRL_T6_TEMP,
	PROGRAMS_ADVTEMPCTRL_T6_DUR,
	PROGRAMS_ADVTEMPCTRL_T6_SETRESET
}MenuFlag;

typedef enum
{
	PENDING = 0,
	STAGE_1,
	STAGE_2,
	STAGE_3,
	STAGE_4,
	STAGE_5,
	STAGE_6,
	FASTSTART,
	ABORT,
}CookingFlag;


#endif /* INC_USERLIBRARIES_COMMON_DEF_H_ */
