/**
 * @file    Helper_Functions.c
 * @brief   Hardware abstraction and display helper functions for the UI layer.
 *
 * This module provides low-level hardware bridge functions required by the
 * U8g2 graphics library when interfacing with the STM32 microcontroller.
 * It includes:
 *
 *  - SPI byte-transfer callback used by U8x8/U8g2 (`u8x8_spi`)
 *  - GPIO and delay callback used by U8x8/U8g2 (`u8x8_gpio_and_delay`)
 *  - Display initialization sequence for the ST7920-based 128x64 LCD
 *    (`Display_Init`)
 *
 * These helper functions act as glue between the U8g2 driver and the STM32 HAL,
 * providing the necessary hardware-specific I/O functionality such as:
 *  - SPI transmission
 *  - Chip-select and reset signaling
 *  - Millisecond delays
 *  - Initial display setup, splash screen, and font configuration
 *
 * All functions in this module are designed to be lightweight and safe to call
 * from the main application loop during display refresh operations.
 *
 * @note This module depends on:
 *       - STM32 HAL (SPI + GPIO)
 *       - U8g2 / U8x8 graphics libraries
 *       - Global SPI and GPIO handles generated by CubeMX
 *
 * @date    03.12.2025
 * @author  Eren Egdemir
 */

#include "Helper_Functions.h"


uint8_t u8x8_spi(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int,
		void *arg_ptr) {

	switch (msg) {
	case U8X8_MSG_BYTE_SET_DC:
		break;
	case U8X8_MSG_BYTE_SEND:
		HAL_SPI_Transmit(&hspi2, (uint8_t *)arg_ptr, arg_int, 1000);
		break;
	case U8X8_MSG_BYTE_START_TRANSFER:
		HAL_GPIO_WritePin(LCD_CS_GPIO_Port, LCD_CS_Pin, GPIO_PIN_SET);
		break;
	case U8X8_MSG_BYTE_END_TRANSFER:
		HAL_GPIO_WritePin(LCD_CS_GPIO_Port, LCD_CS_Pin, GPIO_PIN_RESET);
		break;
	}
	return 1;
}


uint8_t u8x8_gpio_and_delay(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int,
		void *arg_ptr)
{
	switch (msg) {
	case U8X8_MSG_DELAY_MILLI:
		HAL_Delay(arg_int);
		break;
	case U8X8_MSG_GPIO_CS:
		HAL_GPIO_WritePin(LCD_CS_GPIO_Port, LCD_CS_Pin, arg_int);
		break;
	case U8X8_MSG_GPIO_DC:
//		HAL_GPIO_WritePin(DC_GPIO_Port, DC_Pin, arg_int);
		break;
	case U8X8_MSG_GPIO_RESET:
		HAL_GPIO_WritePin(RESET_GPIO_Port, RESET_Pin, arg_int);
		break;
	}
	return 1;
}


void Display_Init(u8g2_t *d){

	u8g2_Setup_st7920_s_128x64_f(d, U8G2_R2, u8x8_spi, u8x8_gpio_and_delay);
	u8g2_InitDisplay(d);
	u8g2_SetPowerSave(d, 0);

	u8g2_ClearDisplay(d);

	u8g2_SendBuffer(d);

	u8g2_ClearBuffer(d);
	u8g2_SetFont(d, u8g2_font_04b_03_tr);
	u8g2_DrawStr(d, 13, 5, "Composite Curing Furnace");
	menu_send_setupLogo(d, 2, 14);
	u8g2_DrawStr(d, 9, 62, "Developed by Eren Egdemir");
	u8g2_DrawStr(d, 45, 12, "Controller");
	u8g2_SendBuffer(d);
	HAL_Delay(1500);

}
